### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [MarinaKruglova/bsa-home-01#1]
Hey, @MarinaKruglova, how about adding a **README.md** with a short description of this repository?
І як воно взагалі, получається ніби?

**Comment by MarinaKruglova** [comment]
Hey @volodymyr-kushnir, just forgot about it. Will take care of it. Thanks for such short notice! :)
Нібі трохи виходить :)

**Comment by volodymyr-kushnir** [comment]
@MarinaKruglova успєх (: ну, ось ще [**лайфхаки і підказки**](https://github.com/volodymyr-kushnir/agenda), якби виникли труднощі чи питання, то гукни @volodymyr-kushnir

**Comment by volodymyr-kushnir** [comment]
Fixed in 6b2bd59d8516f372dd583131c3002b4411a389ba, issue resolved

**Comment by MarinaKruglova** [comment]
Дякую за підказки, Виконано

**Comment by volodymyr-kushnir** [comment]
@MarinaKruglova нема проблем, ще б якби ви додали себе як **Assignee** до цієї проблеми і тегнули її лейблом **enhancement** — було б взагалі чудово

**Comment by MarinaKruglova** [comment]
Дякую за підказку!
